Project1:对文件diabetes.csv中的数据进行处理，将文件夹pima-diabetes放在E：盘的input文件夹下

In [1]:
from pandas import *
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib notebook
from scipy.stats import mode

import os
print(os.listdir("/home/buibui/桌面/input"))

['bike-sharing-dataset', 'heart.csv', 'data.csv', 'pima-diabetes']

In [2]:
################################读入diabetes.csv文件到diabetes################################### 
diabetes = pd.read_csv('/home/buibui/桌面/input/pima-diabetes/diabetes.csv')
################################读入diabetes.csv文件到diabetes###################################

In [3]:
################################显示diabetes的前5行################################### 
diabetes.head(5)
################################显示diabetes的前5行###################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Check for Summary Statistics

In [4]:
################################显示diabetes的详细信息，包括样本数、均值、方差等等################################## 
diabetes.describe()
################################显示diabetes的详细信息，包括样本数、均值、方差等等##################################

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [5]:
################################显示diabetes中Outcome列中每种值出现的次数################################## 
diabetes["Outcome"].value_counts()
################################显示diabetes中Outcome列中每种值出现的次数##################################

0    500
1    268
Name: Outcome, dtype: int64

### Check missing values

In [6]:
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
################################显示diabetes中所有列的标题名################################## 
diabetes.columns
################################显示diabetes中所有列的标题名##################################

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [8]:
################################显示diabetes中所有列的值里面为0的个数################################## 
print((diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age']] == 0).sum())
################################显示diabetes中所有列的值里面为0的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
dtype: int64

In [9]:
################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.loc[:,['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']] = diabetes[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI']].replace(0, np.NaN)

################################将diabetes中所有列的值中为0的值替换为NaN################################## 
diabetes.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1.0,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8.0,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1.0,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,NaN,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [10]:
################################统计diabetes中所有列的值中为null的个数################################## 
diabetes.isnull().sum()
################################统计diabetes中所有列的值中为null的个数##################################

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

## Dealing with missing values

## A. Drop rows having NaN

In [11]:
print("Size before dropping NaN rows",diabetes.shape,"\n")

################################将diabetes中包含NaN的行删掉################################## 
nan_dropped = diabetes.dropna()

################################将diabetes中包含NaN的行删掉################################## 
print(nan_dropped.isnull().sum())
print("\nSize after dropping NaN rows",nan_dropped.shape)

Size before dropping NaN rows (768, 9)

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

Size after dropping NaN rows (336, 9)

### **Project2、数据分析的一系列问题**

In [12]:
vector = np.random.chisquare(1,500)
print(vector)
################################打印vector的均值################################## 
print("Mean",np.mean(vector))
################################打印vector的均值################################## 

print("SD",np.std(vector))
print("Range",max(vector)-min(vector))

[4.17053032e-01 7.37527540e+00 5.37622058e-01 1.00713719e+00
 3.73553974e-04 9.10445317e-01 2.94279941e+00 1.86612910e+00
 7.79037063e-02 8.93073405e-01 1.90002215e+00 5.20274498e-04
 8.01448003e-03 2.15073817e+00 7.49723096e-04 7.61302303e-01
 9.91580423e-02 1.59177497e+00 3.53722217e+00 3.82681530e-01
 5.67998923e-01 5.21418673e-02 5.83444222e-01 1.20316338e-01
 7.87534307e-01 4.42467033e-02 2.66938458e+00 3.21424362e-01
 4.18221087e-02 2.23121739e+00 6.14456780e-02 2.34360145e+00
 1.69676760e-01 1.02065101e+00 2.38302642e-01 9.27439463e+00
 4.31915428e-02 2.25700355e-01 9.19651635e-01 1.88514991e+00
 1.54158764e+00 2.82067877e-03 1.64185959e-01 1.80713493e-01
 1.92906950e-01 8.27072436e-02 2.22491942e+00 7.26007914e-04
 2.27397141e-01 9.76782459e-01 1.37334210e+00 1.04615815e-02
 1.18505028e-01 4.97333523e+00 5.74492538e-01 7.27174520e-01
 5.37257867e-02 9.28177970e+00 3.34004352e-02 1.19748447e-01
 3.49720542e-01 5.43165362e+00 4.39639107e+00 7.48626466e-01
 5.54776935e-03 1.33963109e-01 5.00872256e-03 6.77490156e-01
 5.06598642e-01 6.18965450e+00 1.22689053e+00 1.96639073e-05
 1.13604755e-01 4.21783774e-01 1.98010333e-01 2.17638345e+00
 2.95636397e-01 1.47228861e-02 9.04365003e-04 6.68284155e-01
 5.36095851e-02 1.11401871e-02 5.31652907e-04 3.71053413e-02
 2.08673698e+00 1.13509601e+00 1.55235570e-01 6.31178798e-03
 1.20831538e+00 4.30939348e+00 1.74619057e-01 1.15709323e+00
 8.75790256e-01 9.88282078e-01 1.30495690e+00 5.81536945e-02
 8.97410550e-02 5.11198886e-02 1.31170190e+00 1.63645565e+00
 7.00462752e-02 5.10159440e+00 3.56645948e+00 3.51384043e-01
 3.24794254e-01 1.02940219e-01 4.48511857e-01 1.93541705e+00
 1.17570381e-02 5.07326339e-02 1.59250181e-02 1.16518061e+00
 4.51705579e-01 1.48821947e-01 1.25433965e+00 1.98044516e+00
 2.61541573e+00 2.96330182e-01 1.10691795e+00 4.33888073e-01
 2.65863637e-02 4.74028682e-01 2.06827057e+00 3.58030722e-02
 5.36984691e-01 1.73143982e+00 2.09846549e-01 3.90959584e-02
 7.54782458e-04 3.79236216e+00 1.00892705e-01 1.02281067e-01
 4.33165169e-01 3.04284061e-02 8.25413391e-02 3.53078524e-01
 3.54806208e-02 1.48268323e+00 1.19187380e+00 2.55835198e-02
 2.55153998e-01 6.46958059e-01 2.41946559e+00 8.69834018e-02
 4.37272814e-01 3.89697111e-01 1.49900323e-03 1.86418152e-01
 2.06698971e+00 5.24168817e-03 3.11973417e-01 1.59511681e+00
 2.07786755e-02 6.01588821e+00 8.39339289e-01 4.21516011e-01
 6.62650128e-02 1.66661137e-01 3.18930622e+00 6.15913104e-01
 2.13244727e-02 6.07198499e-01 2.14950380e+00 3.45364288e+00
 7.11235471e-02 4.15491733e-01 1.57006737e-05 9.22972595e-02
 2.62683247e+00 1.76268149e-01 1.09179362e+00 2.38918788e+00
 1.60017550e+00 4.16401492e+00 7.55681795e-01 1.14566678e-01
 1.68747178e+00 5.13478122e-01 4.22973922e-02 2.05356960e-01
 3.75873597e+00 5.89590042e-01 9.15063207e-04 1.71371674e+00
 1.99680794e-02 2.95644206e-02 3.35243025e+00 1.52369093e-01
 1.68880359e-01 3.07478568e-02 1.78708380e-02 1.39269033e+00
 5.75381367e-01 4.05790401e-01 1.91416535e-02 2.19711350e-04
 2.15047342e+00 3.08349113e-01 1.40789064e+00 2.42650325e-01
 3.26928791e-01 1.34495753e-01 1.98253925e+00 1.29780368e-01
 1.18535128e-02 1.13065648e+00 6.66831859e-01 4.91163672e+00
 2.59707177e-01 2.17206623e-01 1.07023449e-01 7.07164537e-01
 5.96466948e-01 1.29853240e+00 8.44743255e-01 1.77443573e-02
 1.48960824e+00 1.76049351e+00 6.75532076e+00 2.28309129e-01
 8.96046039e-06 4.05456685e-03 4.16203243e-02 3.95637754e-02
 3.47132734e-02 2.42923253e-01 1.13421279e+00 6.92565167e-02
 7.03413890e+00 2.30046846e-01 3.71251390e-01 6.91559871e-02
 3.71754982e-04 1.93159283e+00 2.84145907e+00 1.21005046e-02
 4.80848983e-01 3.20074119e+00 1.22678376e+00 4.16261239e-01
 8.69562788e-02 2.00238799e+00 6.97377286e-01 1.67126214e+00
 2.41053474e+00 3.60297700e-06 1.32033250e-01 3.50517200e+00
 8.14704091e-03 7.41618395e-01 1.24819515e-01 2.48086565e+00
 5.83762653e-03 5.94071620e+00 8.32291244e-01 2.97467817e-03
 4.27842816e+00 6.31619864e-02 2.74143412e+00 5.75940112e-01
 5.78646236e-01 2.06888385e-02 4.68963323e-04 5.38360673e-01
 2.21457117e-01 3.01875443e-01 2.24560261e-01 2.66809889e-01
 8.31860025e-01 1.62100322e-01 3.01143510e-01 8.65812497e-01
 1.22648643e-01 2.76395234e+00 1.06552138e+00 3.30570891e+00
 7.08091981e-03 2.64736510e+00 2.58259553e-01 7.40116090e-01
 3.59804310e-01 1.86200570e-02 5.38655019e-01 5.17188760e-01
 2.32838852e-02 1.87815468e-04 3.57119510e-01 2.92460279e-03
 3.77327754e+00 1.36884544e+00 3.30464398e+00 3.28999251e+00
 1.44384289e+00 1.48098847e-02 8.21339367e-01 8.03107869e-02
 1.12060867e+00 6.72705716e-03 1.26022175e+00 2.35398270e+00
 2.01065835e-01 1.31922007e+00 4.96988968e+00 1.44110328e+00
 1.86058264e+00 6.11485718e-01 9.94729678e-01 2.31951550e+00
 8.41640973e-01 6.03813052e-01 3.00734490e-01 2.36188822e-01
 8.77056385e-02 4.24528863e+00 3.05076379e-01 7.18859307e-01
 1.61312902e-03 3.74072648e-01 5.71428660e-04 2.59491587e-01
 2.51483157e-01 1.56440232e+00 5.19515931e-01 1.02185746e-01
 4.50000271e-01 3.50666881e-02 1.22208441e+01 1.20417288e+00
 2.84380312e+00 1.15057077e-01 1.21018138e+00 2.15616036e-01
 5.95519664e-01 5.56651513e-01 1.97394846e-02 9.15408595e-01
 7.07750477e-01 4.23470176e+00 4.66991020e+00 4.82631814e-01
 1.16120261e-02 3.02526437e+00 4.77926990e+00 1.26861893e+00
 1.63383382e+00 9.55456866e-01 1.85152951e+00 2.26872733e-03
 5.66609613e-08 6.59523165e-01 3.35453944e-01 8.18185087e-01
 3.40139036e+00 1.90196069e+00 6.84562621e-03 4.40682034e-01
 5.02351383e-01 6.34852997e-02 7.11878424e-01 2.17630119e-01
 1.55622912e+00 8.44244478e-01 3.89420302e-05 4.96226386e-01
 4.96577953e+00 1.02534841e+00 2.86597105e-01 3.17590898e+00
 2.08336423e-01 1.89432816e+00 6.22087345e+00 2.28532676e-01
 5.21381380e-02 4.85335191e-04 2.03208794e+00 2.55617818e-01
 1.23357028e+00 1.58352836e+00 9.91526990e-02 5.81873038e-01
 3.61352740e+00 5.60037766e-01 5.15334557e+00 1.08653265e+00
 1.85749662e+00 7.31265631e-01 3.45339756e-01 4.09048753e+00
 1.77543502e+00 3.39019602e-01 5.61149844e-02 1.58530869e-03
 2.99647028e+00 8.55802995e-02 2.48652950e-02 5.08049973e-01
 6.72693599e-01 5.25452380e-01 2.82412749e-01 3.28740142e-01
 5.88258393e+00 5.31521979e-01 6.77198141e-01 1.20082344e+00
 1.27656564e+00 2.90044952e+00 1.08548808e+00 4.35735525e+00
 8.84279964e-01 1.15793611e-02 1.47339042e-01 6.00661159e+00
 6.93645217e-01 5.46707791e-01 1.27201475e-01 3.70095509e-01
 6.03470022e-03 1.16827330e+00 5.69204755e-02 2.21093885e-02
 8.99741124e-01 6.66737088e-01 5.72117423e-01 3.68364882e-06
 1.05168924e+00 1.24796457e+00 1.42107012e-01 1.54693087e+00
 9.14695167e-01 1.18150061e-04 7.93646081e-01 5.92339300e-01
 1.86469609e+00 3.15053226e+00 4.89997791e+00 1.02772706e-02
 4.39012653e-02 3.46043255e-02 3.86998115e-01 1.42950999e-01
 6.57970339e-01 4.52425569e-01 2.00488053e-02 6.02034049e-01
 1.02809220e+00 5.41380377e-02 5.42653243e-04 3.72649349e-01
 1.12521755e-01 1.05799956e+00 3.39482296e-02 7.82321223e-01
 1.54268352e+00 1.78628074e+00 1.59235115e-02 1.08046345e+00
 4.18907480e-01 1.13820504e-01 5.75986729e-01 7.39447675e-01
 1.63469788e+00 2.77567478e+00 3.21511518e-02 1.01058997e+00
 8.32634002e-01 6.25125765e-02 5.29889440e-01 1.10782085e-01
 5.05982678e-02 1.11593984e+00 4.23691013e-03 9.28106435e-01
 1.11636456e+00 2.26770763e-01 4.76806038e-02 1.09016274e+00
 5.75701951e-01 8.59814655e+00 3.60242176e-01 1.96772028e+00
 1.62584716e+00 3.69740446e-02 2.86832376e-01 2.18806942e+00
 2.60394206e-02 1.31435614e-01 2.17663213e+00 1.35981819e+00
 1.83876721e-01 9.45643156e-01 5.15300151e-01 1.98758273e-01
 1.05705037e+00 2.44833618e-02 2.07786449e+00 1.86658687e+00
 8.85212393e-01 1.19811264e+00 1.50789236e+00 3.64966550e-01]
Mean 1.0835508893238972
SD 1.5603037064638459
Range 12.220844022138332

### Reshape

In [13]:
vector.shape

(500,)

In [14]:
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector = vector.reshape(-1,1)
################################将一维向量vector转成大小为500*1的二维向量并赋值给row_vector################################## 
row_vector.shape
print(row_vector)

[[4.17053032e-01]
 [7.37527540e+00]
 [5.37622058e-01]
 [1.00713719e+00]
 [3.73553974e-04]
 [9.10445317e-01]
 [2.94279941e+00]
 [1.86612910e+00]
 [7.79037063e-02]
 [8.93073405e-01]
 [1.90002215e+00]
 [5.20274498e-04]
 [8.01448003e-03]
 [2.15073817e+00]
 [7.49723096e-04]
 [7.61302303e-01]
 [9.91580423e-02]
 [1.59177497e+00]
 [3.53722217e+00]
 [3.82681530e-01]
 [5.67998923e-01]
 [5.21418673e-02]
 [5.83444222e-01]
 [1.20316338e-01]
 [7.87534307e-01]
 [4.42467033e-02]
 [2.66938458e+00]
 [3.21424362e-01]
 [4.18221087e-02]
 [2.23121739e+00]
 [6.14456780e-02]
 [2.34360145e+00]
 [1.69676760e-01]
 [1.02065101e+00]
 [2.38302642e-01]
 [9.27439463e+00]
 [4.31915428e-02]
 [2.25700355e-01]
 [9.19651635e-01]
 [1.88514991e+00]
 [1.54158764e+00]
 [2.82067877e-03]
 [1.64185959e-01]
 [1.80713493e-01]
 [1.92906950e-01]
 [8.27072436e-02]
 [2.22491942e+00]
 [7.26007914e-04]
 [2.27397141e-01]
 [9.76782459e-01]
 [1.37334210e+00]
 [1.04615815e-02]
 [1.18505028e-01]
 [4.97333523e+00]
 [5.74492538e-01]
 [7.27174520e-01]
 [5.37257867e-02]
 [9.28177970e+00]
 [3.34004352e-02]
 [1.19748447e-01]
 [3.49720542e-01]
 [5.43165362e+00]
 [4.39639107e+00]
 [7.48626466e-01]
 [5.54776935e-03]
 [1.33963109e-01]
 [5.00872256e-03]
 [6.77490156e-01]
 [5.06598642e-01]
 [6.18965450e+00]
 [1.22689053e+00]
 [1.96639073e-05]
 [1.13604755e-01]
 [4.21783774e-01]
 [1.98010333e-01]
 [2.17638345e+00]
 [2.95636397e-01]
 [1.47228861e-02]
 [9.04365003e-04]
 [6.68284155e-01]
 [5.36095851e-02]
 [1.11401871e-02]
 [5.31652907e-04]
 [3.71053413e-02]
 [2.08673698e+00]
 [1.13509601e+00]
 [1.55235570e-01]
 [6.31178798e-03]
 [1.20831538e+00]
 [4.30939348e+00]
 [1.74619057e-01]
 [1.15709323e+00]
 [8.75790256e-01]
 [9.88282078e-01]
 [1.30495690e+00]
 [5.81536945e-02]
 [8.97410550e-02]
 [5.11198886e-02]
 [1.31170190e+00]
 [1.63645565e+00]
 [7.00462752e-02]
 [5.10159440e+00]
 [3.56645948e+00]
 [3.51384043e-01]
 [3.24794254e-01]
 [1.02940219e-01]
 [4.48511857e-01]
 [1.93541705e+00]
 [1.17570381e-02]
 [5.07326339e-02]
 [1.59250181e-02]
 [1.16518061e+00]
 [4.51705579e-01]
 [1.48821947e-01]
 [1.25433965e+00]
 [1.98044516e+00]
 [2.61541573e+00]
 [2.96330182e-01]
 [1.10691795e+00]
 [4.33888073e-01]
 [2.65863637e-02]
 [4.74028682e-01]
 [2.06827057e+00]
 [3.58030722e-02]
 [5.36984691e-01]
 [1.73143982e+00]
 [2.09846549e-01]
 [3.90959584e-02]
 [7.54782458e-04]
 [3.79236216e+00]
 [1.00892705e-01]
 [1.02281067e-01]
 [4.33165169e-01]
 [3.04284061e-02]
 [8.25413391e-02]
 [3.53078524e-01]
 [3.54806208e-02]
 [1.48268323e+00]
 [1.19187380e+00]
 [2.55835198e-02]
 [2.55153998e-01]
 [6.46958059e-01]
 [2.41946559e+00]
 [8.69834018e-02]
 [4.37272814e-01]
 [3.89697111e-01]
 [1.49900323e-03]
 [1.86418152e-01]
 [2.06698971e+00]
 [5.24168817e-03]
 [3.11973417e-01]
 [1.59511681e+00]
 [2.07786755e-02]
 [6.01588821e+00]
 [8.39339289e-01]
 [4.21516011e-01]
 [6.62650128e-02]
 [1.66661137e-01]
 [3.18930622e+00]
 [6.15913104e-01]
 [2.13244727e-02]
 [6.07198499e-01]
 [2.14950380e+00]
 [3.45364288e+00]
 [7.11235471e-02]
 [4.15491733e-01]
 [1.57006737e-05]
 [9.22972595e-02]
 [2.62683247e+00]
 [1.76268149e-01]
 [1.09179362e+00]
 [2.38918788e+00]
 [1.60017550e+00]
 [4.16401492e+00]
 [7.55681795e-01]
 [1.14566678e-01]
 [1.68747178e+00]
 [5.13478122e-01]
 [4.22973922e-02]
 [2.05356960e-01]
 [3.75873597e+00]
 [5.89590042e-01]
 [9.15063207e-04]
 [1.71371674e+00]
 [1.99680794e-02]
 [2.95644206e-02]
 [3.35243025e+00]
 [1.52369093e-01]
 [1.68880359e-01]
 [3.07478568e-02]
 [1.78708380e-02]
 [1.39269033e+00]
 [5.75381367e-01]
 [4.05790401e-01]
 [1.91416535e-02]
 [2.19711350e-04]
 [2.15047342e+00]
 [3.08349113e-01]
 [1.40789064e+00]
 [2.42650325e-01]
 [3.26928791e-01]
 [1.34495753e-01]
 [1.98253925e+00]
 [1.29780368e-01]
 [1.18535128e-02]
 [1.13065648e+00]
 [6.66831859e-01]
 [4.91163672e+00]
 [2.59707177e-01]
 [2.17206623e-01]
 [1.07023449e-01]
 [7.07164537e-01]
 [5.96466948e-01]
 [1.29853240e+00]
 [8.44743255e-01]
 [1.77443573e-02]
 [1.48960824e+00]
 [1.76049351e+00]
 [6.75532076e+00]
 [2.28309129e-01]
 [8.96046039e-06]
 [4.05456685e-03]
 [4.16203243e-02]
 [3.95637754e-02]
 [3.47132734e-02]
 [2.42923253e-01]
 [1.13421279e+00]
 [6.92565167e-02]
 [7.03413890e+00]
 [2.30046846e-01]
 [3.71251390e-01]
 [6.91559871e-02]
 [3.71754982e-04]
 [1.93159283e+00]
 [2.84145907e+00]
 [1.21005046e-02]
 [4.80848983e-01]
 [3.20074119e+00]
 [1.22678376e+00]
 [4.16261239e-01]
 [8.69562788e-02]
 [2.00238799e+00]
 [6.97377286e-01]
 [1.67126214e+00]
 [2.41053474e+00]
 [3.60297700e-06]
 [1.32033250e-01]
 [3.50517200e+00]
 [8.14704091e-03]
 [7.41618395e-01]
 [1.24819515e-01]
 [2.48086565e+00]
 [5.83762653e-03]
 [5.94071620e+00]
 [8.32291244e-01]
 [2.97467817e-03]
 [4.27842816e+00]
 [6.31619864e-02]
 [2.74143412e+00]
 [5.75940112e-01]
 [5.78646236e-01]
 [2.06888385e-02]
 [4.68963323e-04]
 [5.38360673e-01]
 [2.21457117e-01]
 [3.01875443e-01]
 [2.24560261e-01]
 [2.66809889e-01]
 [8.31860025e-01]
 [1.62100322e-01]
 [3.01143510e-01]
 [8.65812497e-01]
 [1.22648643e-01]
 [2.76395234e+00]
 [1.06552138e+00]
 [3.30570891e+00]
 [7.08091981e-03]
 [2.64736510e+00]
 [2.58259553e-01]
 [7.40116090e-01]
 [3.59804310e-01]
 [1.86200570e-02]
 [5.38655019e-01]
 [5.17188760e-01]
 [2.32838852e-02]
 [1.87815468e-04]
 [3.57119510e-01]
 [2.92460279e-03]
 [3.77327754e+00]
 [1.36884544e+00]
 [3.30464398e+00]
 [3.28999251e+00]
 [1.44384289e+00]
 [1.48098847e-02]
 [8.21339367e-01]
 [8.03107869e-02]
 [1.12060867e+00]
 [6.72705716e-03]
 [1.26022175e+00]
 [2.35398270e+00]
 [2.01065835e-01]
 [1.31922007e+00]
 [4.96988968e+00]
 [1.44110328e+00]
 [1.86058264e+00]
 [6.11485718e-01]
 [9.94729678e-01]
 [2.31951550e+00]
 [8.41640973e-01]
 [6.03813052e-01]
 [3.00734490e-01]
 [2.36188822e-01]
 [8.77056385e-02]
 [4.24528863e+00]
 [3.05076379e-01]
 [7.18859307e-01]
 [1.61312902e-03]
 [3.74072648e-01]
 [5.71428660e-04]
 [2.59491587e-01]
 [2.51483157e-01]
 [1.56440232e+00]
 [5.19515931e-01]
 [1.02185746e-01]
 [4.50000271e-01]
 [3.50666881e-02]
 [1.22208441e+01]
 [1.20417288e+00]
 [2.84380312e+00]
 [1.15057077e-01]
 [1.21018138e+00]
 [2.15616036e-01]
 [5.95519664e-01]
 [5.56651513e-01]
 [1.97394846e-02]
 [9.15408595e-01]
 [7.07750477e-01]
 [4.23470176e+00]
 [4.66991020e+00]
 [4.82631814e-01]
 [1.16120261e-02]
 [3.02526437e+00]
 [4.77926990e+00]
 [1.26861893e+00]
 [1.63383382e+00]
 [9.55456866e-01]
 [1.85152951e+00]
 [2.26872733e-03]
 [5.66609613e-08]
 [6.59523165e-01]
 [3.35453944e-01]
 [8.18185087e-01]
 [3.40139036e+00]
 [1.90196069e+00]
 [6.84562621e-03]
 [4.40682034e-01]
 [5.02351383e-01]
 [6.34852997e-02]
 [7.11878424e-01]
 [2.17630119e-01]
 [1.55622912e+00]
 [8.44244478e-01]
 [3.89420302e-05]
 [4.96226386e-01]
 [4.96577953e+00]
 [1.02534841e+00]
 [2.86597105e-01]
 [3.17590898e+00]
 [2.08336423e-01]
 [1.89432816e+00]
 [6.22087345e+00]
 [2.28532676e-01]
 [5.21381380e-02]
 [4.85335191e-04]
 [2.03208794e+00]
 [2.55617818e-01]
 [1.23357028e+00]
 [1.58352836e+00]
 [9.91526990e-02]
 [5.81873038e-01]
 [3.61352740e+00]
 [5.60037766e-01]
 [5.15334557e+00]
 [1.08653265e+00]
 [1.85749662e+00]
 [7.31265631e-01]
 [3.45339756e-01]
 [4.09048753e+00]
 [1.77543502e+00]
 [3.39019602e-01]
 [5.61149844e-02]
 [1.58530869e-03]
 [2.99647028e+00]
 [8.55802995e-02]
 [2.48652950e-02]
 [5.08049973e-01]
 [6.72693599e-01]
 [5.25452380e-01]
 [2.82412749e-01]
 [3.28740142e-01]
 [5.88258393e+00]
 [5.31521979e-01]
 [6.77198141e-01]
 [1.20082344e+00]
 [1.27656564e+00]
 [2.90044952e+00]
 [1.08548808e+00]
 [4.35735525e+00]
 [8.84279964e-01]
 [1.15793611e-02]
 [1.47339042e-01]
 [6.00661159e+00]
 [6.93645217e-01]
 [5.46707791e-01]
 [1.27201475e-01]
 [3.70095509e-01]
 [6.03470022e-03]
 [1.16827330e+00]
 [5.69204755e-02]
 [2.21093885e-02]
 [8.99741124e-01]
 [6.66737088e-01]
 [5.72117423e-01]
 [3.68364882e-06]
 [1.05168924e+00]
 [1.24796457e+00]
 [1.42107012e-01]
 [1.54693087e+00]
 [9.14695167e-01]
 [1.18150061e-04]
 [7.93646081e-01]
 [5.92339300e-01]
 [1.86469609e+00]
 [3.15053226e+00]
 [4.89997791e+00]
 [1.02772706e-02]
 [4.39012653e-02]
 [3.46043255e-02]
 [3.86998115e-01]
 [1.42950999e-01]
 [6.57970339e-01]
 [4.52425569e-01]
 [2.00488053e-02]
 [6.02034049e-01]
 [1.02809220e+00]
 [5.41380377e-02]
 [5.42653243e-04]
 [3.72649349e-01]
 [1.12521755e-01]
 [1.05799956e+00]
 [3.39482296e-02]
 [7.82321223e-01]
 [1.54268352e+00]
 [1.78628074e+00]
 [1.59235115e-02]
 [1.08046345e+00]
 [4.18907480e-01]
 [1.13820504e-01]
 [5.75986729e-01]
 [7.39447675e-01]
 [1.63469788e+00]
 [2.77567478e+00]
 [3.21511518e-02]
 [1.01058997e+00]
 [8.32634002e-01]
 [6.25125765e-02]
 [5.29889440e-01]
 [1.10782085e-01]
 [5.05982678e-02]
 [1.11593984e+00]
 [4.23691013e-03]
 [9.28106435e-01]
 [1.11636456e+00]
 [2.26770763e-01]
 [4.76806038e-02]
 [1.09016274e+00]
 [5.75701951e-01]
 [8.59814655e+00]
 [3.60242176e-01]
 [1.96772028e+00]
 [1.62584716e+00]
 [3.69740446e-02]
 [2.86832376e-01]
 [2.18806942e+00]
 [2.60394206e-02]
 [1.31435614e-01]
 [2.17663213e+00]
 [1.35981819e+00]
 [1.83876721e-01]
 [9.45643156e-01]
 [5.15300151e-01]
 [1.98758273e-01]
 [1.05705037e+00]
 [2.44833618e-02]
 [2.07786449e+00]
 [1.86658687e+00]
 [8.85212393e-01]
 [1.19811264e+00]
 [1.50789236e+00]
 [3.64966550e-01]]

In [15]:
col_vector = vector.reshape(1,-1)
col_vector.shape

(1, 500)

In [16]:
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix = vector.reshape(10,50)
################################将一维向量vector转成大小为10*50的二维向量并赋值给maxtrix################################## 
matrix.shape
print(matrix)

[[4.17053032e-01 7.37527540e+00 5.37622058e-01 1.00713719e+00
  3.73553974e-04 9.10445317e-01 2.94279941e+00 1.86612910e+00
  7.79037063e-02 8.93073405e-01 1.90002215e+00 5.20274498e-04
  8.01448003e-03 2.15073817e+00 7.49723096e-04 7.61302303e-01
  9.91580423e-02 1.59177497e+00 3.53722217e+00 3.82681530e-01
  5.67998923e-01 5.21418673e-02 5.83444222e-01 1.20316338e-01
  7.87534307e-01 4.42467033e-02 2.66938458e+00 3.21424362e-01
  4.18221087e-02 2.23121739e+00 6.14456780e-02 2.34360145e+00
  1.69676760e-01 1.02065101e+00 2.38302642e-01 9.27439463e+00
  4.31915428e-02 2.25700355e-01 9.19651635e-01 1.88514991e+00
  1.54158764e+00 2.82067877e-03 1.64185959e-01 1.80713493e-01
  1.92906950e-01 8.27072436e-02 2.22491942e+00 7.26007914e-04
  2.27397141e-01 9.76782459e-01]
 [1.37334210e+00 1.04615815e-02 1.18505028e-01 4.97333523e+00
  5.74492538e-01 7.27174520e-01 5.37257867e-02 9.28177970e+00
  3.34004352e-02 1.19748447e-01 3.49720542e-01 5.43165362e+00
  4.39639107e+00 7.48626466e-01 5.54776935e-03 1.33963109e-01
  5.00872256e-03 6.77490156e-01 5.06598642e-01 6.18965450e+00
  1.22689053e+00 1.96639073e-05 1.13604755e-01 4.21783774e-01
  1.98010333e-01 2.17638345e+00 2.95636397e-01 1.47228861e-02
  9.04365003e-04 6.68284155e-01 5.36095851e-02 1.11401871e-02
  5.31652907e-04 3.71053413e-02 2.08673698e+00 1.13509601e+00
  1.55235570e-01 6.31178798e-03 1.20831538e+00 4.30939348e+00
  1.74619057e-01 1.15709323e+00 8.75790256e-01 9.88282078e-01
  1.30495690e+00 5.81536945e-02 8.97410550e-02 5.11198886e-02
  1.31170190e+00 1.63645565e+00]
 [7.00462752e-02 5.10159440e+00 3.56645948e+00 3.51384043e-01
  3.24794254e-01 1.02940219e-01 4.48511857e-01 1.93541705e+00
  1.17570381e-02 5.07326339e-02 1.59250181e-02 1.16518061e+00
  4.51705579e-01 1.48821947e-01 1.25433965e+00 1.98044516e+00
  2.61541573e+00 2.96330182e-01 1.10691795e+00 4.33888073e-01
  2.65863637e-02 4.74028682e-01 2.06827057e+00 3.58030722e-02
  5.36984691e-01 1.73143982e+00 2.09846549e-01 3.90959584e-02
  7.54782458e-04 3.79236216e+00 1.00892705e-01 1.02281067e-01
  4.33165169e-01 3.04284061e-02 8.25413391e-02 3.53078524e-01
  3.54806208e-02 1.48268323e+00 1.19187380e+00 2.55835198e-02
  2.55153998e-01 6.46958059e-01 2.41946559e+00 8.69834018e-02
  4.37272814e-01 3.89697111e-01 1.49900323e-03 1.86418152e-01
  2.06698971e+00 5.24168817e-03]
 [3.11973417e-01 1.59511681e+00 2.07786755e-02 6.01588821e+00
  8.39339289e-01 4.21516011e-01 6.62650128e-02 1.66661137e-01
  3.18930622e+00 6.15913104e-01 2.13244727e-02 6.07198499e-01
  2.14950380e+00 3.45364288e+00 7.11235471e-02 4.15491733e-01
  1.57006737e-05 9.22972595e-02 2.62683247e+00 1.76268149e-01
  1.09179362e+00 2.38918788e+00 1.60017550e+00 4.16401492e+00
  7.55681795e-01 1.14566678e-01 1.68747178e+00 5.13478122e-01
  4.22973922e-02 2.05356960e-01 3.75873597e+00 5.89590042e-01
  9.15063207e-04 1.71371674e+00 1.99680794e-02 2.95644206e-02
  3.35243025e+00 1.52369093e-01 1.68880359e-01 3.07478568e-02
  1.78708380e-02 1.39269033e+00 5.75381367e-01 4.05790401e-01
  1.91416535e-02 2.19711350e-04 2.15047342e+00 3.08349113e-01
  1.40789064e+00 2.42650325e-01]
 [3.26928791e-01 1.34495753e-01 1.98253925e+00 1.29780368e-01
  1.18535128e-02 1.13065648e+00 6.66831859e-01 4.91163672e+00
  2.59707177e-01 2.17206623e-01 1.07023449e-01 7.07164537e-01
  5.96466948e-01 1.29853240e+00 8.44743255e-01 1.77443573e-02
  1.48960824e+00 1.76049351e+00 6.75532076e+00 2.28309129e-01
  8.96046039e-06 4.05456685e-03 4.16203243e-02 3.95637754e-02
  3.47132734e-02 2.42923253e-01 1.13421279e+00 6.92565167e-02
  7.03413890e+00 2.30046846e-01 3.71251390e-01 6.91559871e-02
  3.71754982e-04 1.93159283e+00 2.84145907e+00 1.21005046e-02
  4.80848983e-01 3.20074119e+00 1.22678376e+00 4.16261239e-01
  8.69562788e-02 2.00238799e+00 6.97377286e-01 1.67126214e+00
  2.41053474e+00 3.60297700e-06 1.32033250e-01 3.50517200e+00
  8.14704091e-03 7.41618395e-01]
 [1.24819515e-01 2.48086565e+00 5.83762653e-03 5.94071620e+00
  8.32291244e-01 2.97467817e-03 4.27842816e+00 6.31619864e-02
  2.74143412e+00 5.75940112e-01 5.78646236e-01 2.06888385e-02
  4.68963323e-04 5.38360673e-01 2.21457117e-01 3.01875443e-01
  2.24560261e-01 2.66809889e-01 8.31860025e-01 1.62100322e-01
  3.01143510e-01 8.65812497e-01 1.22648643e-01 2.76395234e+00
  1.06552138e+00 3.30570891e+00 7.08091981e-03 2.64736510e+00
  2.58259553e-01 7.40116090e-01 3.59804310e-01 1.86200570e-02
  5.38655019e-01 5.17188760e-01 2.32838852e-02 1.87815468e-04
  3.57119510e-01 2.92460279e-03 3.77327754e+00 1.36884544e+00
  3.30464398e+00 3.28999251e+00 1.44384289e+00 1.48098847e-02
  8.21339367e-01 8.03107869e-02 1.12060867e+00 6.72705716e-03
  1.26022175e+00 2.35398270e+00]
 [2.01065835e-01 1.31922007e+00 4.96988968e+00 1.44110328e+00
  1.86058264e+00 6.11485718e-01 9.94729678e-01 2.31951550e+00
  8.41640973e-01 6.03813052e-01 3.00734490e-01 2.36188822e-01
  8.77056385e-02 4.24528863e+00 3.05076379e-01 7.18859307e-01
  1.61312902e-03 3.74072648e-01 5.71428660e-04 2.59491587e-01
  2.51483157e-01 1.56440232e+00 5.19515931e-01 1.02185746e-01
  4.50000271e-01 3.50666881e-02 1.22208441e+01 1.20417288e+00
  2.84380312e+00 1.15057077e-01 1.21018138e+00 2.15616036e-01
  5.95519664e-01 5.56651513e-01 1.97394846e-02 9.15408595e-01
  7.07750477e-01 4.23470176e+00 4.66991020e+00 4.82631814e-01
  1.16120261e-02 3.02526437e+00 4.77926990e+00 1.26861893e+00
  1.63383382e+00 9.55456866e-01 1.85152951e+00 2.26872733e-03
  5.66609613e-08 6.59523165e-01]
 [3.35453944e-01 8.18185087e-01 3.40139036e+00 1.90196069e+00
  6.84562621e-03 4.40682034e-01 5.02351383e-01 6.34852997e-02
  7.11878424e-01 2.17630119e-01 1.55622912e+00 8.44244478e-01
  3.89420302e-05 4.96226386e-01 4.96577953e+00 1.02534841e+00
  2.86597105e-01 3.17590898e+00 2.08336423e-01 1.89432816e+00
  6.22087345e+00 2.28532676e-01 5.21381380e-02 4.85335191e-04
  2.03208794e+00 2.55617818e-01 1.23357028e+00 1.58352836e+00
  9.91526990e-02 5.81873038e-01 3.61352740e+00 5.60037766e-01
  5.15334557e+00 1.08653265e+00 1.85749662e+00 7.31265631e-01
  3.45339756e-01 4.09048753e+00 1.77543502e+00 3.39019602e-01
  5.61149844e-02 1.58530869e-03 2.99647028e+00 8.55802995e-02
  2.48652950e-02 5.08049973e-01 6.72693599e-01 5.25452380e-01
  2.82412749e-01 3.28740142e-01]
 [5.88258393e+00 5.31521979e-01 6.77198141e-01 1.20082344e+00
  1.27656564e+00 2.90044952e+00 1.08548808e+00 4.35735525e+00
  8.84279964e-01 1.15793611e-02 1.47339042e-01 6.00661159e+00
  6.93645217e-01 5.46707791e-01 1.27201475e-01 3.70095509e-01
  6.03470022e-03 1.16827330e+00 5.69204755e-02 2.21093885e-02
  8.99741124e-01 6.66737088e-01 5.72117423e-01 3.68364882e-06
  1.05168924e+00 1.24796457e+00 1.42107012e-01 1.54693087e+00
  9.14695167e-01 1.18150061e-04 7.93646081e-01 5.92339300e-01
  1.86469609e+00 3.15053226e+00 4.89997791e+00 1.02772706e-02
  4.39012653e-02 3.46043255e-02 3.86998115e-01 1.42950999e-01
  6.57970339e-01 4.52425569e-01 2.00488053e-02 6.02034049e-01
  1.02809220e+00 5.41380377e-02 5.42653243e-04 3.72649349e-01
  1.12521755e-01 1.05799956e+00]
 [3.39482296e-02 7.82321223e-01 1.54268352e+00 1.78628074e+00
  1.59235115e-02 1.08046345e+00 4.18907480e-01 1.13820504e-01
  5.75986729e-01 7.39447675e-01 1.63469788e+00 2.77567478e+00
  3.21511518e-02 1.01058997e+00 8.32634002e-01 6.25125765e-02
  5.29889440e-01 1.10782085e-01 5.05982678e-02 1.11593984e+00
  4.23691013e-03 9.28106435e-01 1.11636456e+00 2.26770763e-01
  4.76806038e-02 1.09016274e+00 5.75701951e-01 8.59814655e+00
  3.60242176e-01 1.96772028e+00 1.62584716e+00 3.69740446e-02
  2.86832376e-01 2.18806942e+00 2.60394206e-02 1.31435614e-01
  2.17663213e+00 1.35981819e+00 1.83876721e-01 9.45643156e-01
  5.15300151e-01 1.98758273e-01 1.05705037e+00 2.44833618e-02
  2.07786449e+00 1.86658687e+00 8.85212393e-01 1.19811264e+00
  1.50789236e+00 3.64966550e-01]]

### Pivot Table

In [17]:
#Determine pivot table
df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
                       "bar", "bar", "bar", "bar"],
                    "B": ["one", "one", "one", "two", "two",
                          "one", "one", "two", "two"],
                    "C": ["small", "large", "large", "small",
                          "small", "large", "small", "small",
                          "large"],
                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

In [18]:
df.head(9)

     A    B      C  D  E
0  foo  one  small  1  2
1  foo  one  large  2  4
2  foo  one  large  2  5
3  foo  two  small  3  5
4  foo  two  small  3  6
5  bar  one  large  4  6
6  bar  one  small  5  8
7  bar  two  small  6  9
8  bar  two  large  7  9

In [19]:
###################################想办法生成以下表格，行为A、B，列为C###################################
table = pivot_table(df, values='D', index=['A', 'B'],
                  columns=['C'], aggfunc=np.sum)

###################################想办法生成以下表格，行为A、B，列为C###################################
table

C        large  small
A   B
bar one    4.0    5.0
    two    7.0    6.0
foo one    4.0    1.0
    two    NaN    6.0

### Merging dataframes

In [20]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                        'B': ['B0', 'B1', 'B2', 'B3'],
                        'C': ['C0', 'C1', 'C2', 'C3'],
                        'D': ['D0', 'D1', 'D2', 'D3']},
                       index=[0, 1, 2, 3])
    

df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                        'B': ['B4', 'B5', 'B6', 'B7'],
                        'C': ['C4', 'C5', 'C6', 'C7'],
                        'D': ['D4', 'D5', 'D6', 'D7']},
                       index=[4, 5, 6, 7])
    

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                       'B': ['B8', 'B9', 'B10', 'B11'],
                        'C': ['C8', 'C9', 'C10', 'C11'],
                        'D': ['D8', 'D9', 'D10', 'D11']},
                       index=[8, 9, 10, 11])
    
###################################将df1,df2,df3按行拼接到一起，并赋给result###################################
frames = [df1, df2, df3]

result = pd.concat(frames)

###################################将df1,df2,df3按行拼接到一起，并赋给result####################################

print(result)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11